server:
  port: 9094
  
spring:
  data:
    mongodb:
      uri: mongodb://mongoonbrd:mongoonbrd@docdb-2023-05-11-18-02-52.c9bnvhq6g6em.ap-south-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&retryWrites=false
      database : test
      ssl:
        enabled: true
        invalidHostNameAllowed: true
        trust-store: /rds-truststore.jks
        trust-store-password: mnbvcxz
  application:
    name: ONBOARDING-TASK
  config:
    import: optional:configserver:http://localhost:9296/